// livros-react/src/LivroLista.js
import React, { useState, useEffect, useMemo } from "react";
import ControleLivro from "./control/ControleLivros.ts";
import ControleEditora from "./control/ControleEditora.ts";

const LinhaLivro = ({ livro, excluir, controleEditora, index }) => {
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr>
      <th scope="row">
        <div className="flex flex-column">
          <div>{livro.titulo}</div>
          <button
            className="btn btn-danger"
            onClick={() => excluir(livro.codigo)}
          >
            Excluir
          </button>
        </div>
      </th>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista = () => {
  const controleLivro = useMemo(() => new ControleLivro(), []); 
  const controleEditora = useMemo(() => new ControleEditora(), []); 

  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      controleLivro.obterLivros().then((livrosCarregados) => {
        setLivros(livrosCarregados);
        setCarregado(true);
      });
    }
  }, [carregado, controleLivro]);

  const excluirLivro = (codigoLivro) => {
    controleLivro.excluir(codigoLivro).then(() => {
      setCarregado(false);
    });
  };

  return (
    <main className="container">
      <div className="row justify-content-center">
        <div className="col-12">
          <h1 className="text-center my-3">Lista de Livros</h1>
        </div>
      </div>
      <div className="row justify-content-center">
        <div className="col-12">
          <table className="table table-striped">
            <thead className="table-dark">
              <tr>
                <th scope="col">Título</th>
                <th scope="col">Resumo</th>
                <th scope="col">Editora</th>
                <th scope="col">Autores</th>
              </tr>
            </thead>
            <tbody className="my-5">
              {livros.map((livro) => (
                <LinhaLivro
                  key={livro.codigo}
                  livro={livro}
                  excluir={excluirLivro}
                  controleEditora={controleEditora}
                />
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
};

export default LivroLista;

// livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      })
    })
  }

  obterNome = (codEditora: number): string => {
    console.log('Getting name for codEditora:', codEditora);
    const nomeEditora = this.servEditora.getNomeEditora(codEditora);
    console.log('Found name:', nomeEditora);
    return nomeEditora;
  }
  
}

<main class="container">
  <h1 class="my-3">Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          <div class="d-flex flex-column">
            {{ livro.titulo }}
            <button class="btn btn-danger mt-2" (click)="excluir(livro.codigo)">Excluir</button>
          </div>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
