// livros-react/src/LivroDados.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import ControleLivro from "./control/ControleLivros.ts";
import ControleEditora from "./control/ControleEditora.ts";

const LivroDados = () => {
  const navigate = useNavigate();
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(0);

  const controleEditora = new ControleEditora();
  const controleLivro = new ControleLivro();

  let opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const tratarCombo = (event) => {
    const value = parseInt(event.target.value);
    setCodEditora(value);
  };

  const incluir = (event) => {
    event.preventDefault();
    const autoresArray = autores.split("\n").map((item) => item.trim());
    const novoLivro = {
      codigo: "",
      titulo: titulo,
      resumo: resumo,
      autores: autoresArray,
      codEditora: codEditora,
    };
    controleLivro.incluir(novoLivro).then(() => {
      navigate("/");
    });
  };

  return (
    <main class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <h1 class="text-center mt-4">Dados do Livro</h1>
          <form onSubmit={incluir}>
            <div class="mb-3">
              <label for="titulo" class="form-label">
                Título:
              </label>
              <input
                id="titulo"
                class="form-control"
                type="text"
                value={titulo}
                onChange={(e) => setTitulo(e.target.value)}
              />
            </div>
            <div class="mb-3">
              <label for="resumo" class="form-label">
                Resumo:
              </label>
              <textarea
                id="resumo"
                class="form-control"
                value={resumo}
                onChange={(e) => setResumo(e.target.value)}
              ></textarea>
            </div>
            <div class="mb-3">
              <label for="autores" class="form-label">
                Autores:
              </label>
              <textarea
                id="autores"
                class="form-control"
                value={autores}
                onChange={(e) => setAutores(e.target.value)}
              ></textarea>
            </div>
            <div class="mb-3">
              <label for="editora" class="form-label">
                Editora:
              </label>
              <select
                id="editora"
                class="form-select"
                value={codEditora}
                onChange={tratarCombo}
              >
                {opcoes.map((opcao) => (
                  <option key={opcao.value} value={opcao.value}>
                    {opcao.text}
                  </option>
                ))}
              </select>
            </div>
            <div class="text-center">
              <button class="btn btn-primary" type="submit">
                Salvar Dados
              </button>
            </div>
          </form>
        </div>
      </div>
    </main>
  );
};

export default LivroDados;

// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro;
  autoresForm: string = '';
  editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = async (): Promise<void> => {
    this.livro.autores = this.autoresForm.split('\n');
    await this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container">
  <h1 class="my-3">Cadastro de Livros</h1>
  
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" class="form-control" id="titulo" name="titulo" [(ngModel)]="livro.titulo" required>
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" rows="3" required></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
        <option *ngFor="let editora of editoras" [ngValue]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</main>
